- name: Catalogue Scripts 
  hosts: catalogue
  become: yes
  tasks:
    - name: Disable old nodeJS and enable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
    - name: Install Node JS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add user
      ansible.builtin.user:
        name: roboshop

    - name: create directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: Download appliacation code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
      
    - name: unzip the file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app

    